server:
  port: @server.port@
  rest:
    port: @server.rest.port@
    endpoint: api/v1
spring:
  application:
    name: @project.name@
info:
  version: @project.version@
  damsel:
    version: @damsel.version@
springfox:
  documentation:
    swagger:
      v2:
        path: /${server.rest.endpoint}/swag
samsung:
  version: v1
  endpoint: api-ops.mpay.samsung.com
  url:
    template:
      transactions: https://${samsung.endpoint}/ops/${samsung.version}/transactions
      credentials: https://${samsung.endpoint}/ops/${samsung.version}/transactions/paymentCredentials/{id}?serviceId={serviceId}
  timeout:
    connect: 3000
    read: 3000
    write: 3000
keys:
  path:
